version: "3"
services:
  trade_soft:
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongodb:tradesoft_db
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb